'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BangSanPham
    Public Property id As Integer
    Public Property MaSP As String
    Public Property TenSP As String
    Public Property Loai_id As Integer
    Public Property GiaBan As Integer
    Public Property GiaGoc As Integer
    Public Property GiaGop As Integer
    Public Property SoLuongTon As Integer

    Public Overridable Property LoaiSanPham As LoaiSanPham

End Class
