'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class CS4PEEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CS4PEEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property BangSanPhams() As DbSet(Of BangSanPham)
    Public Overridable Property LoaiSanPhams() As DbSet(Of LoaiSanPham)

End Class
